### ISSUE TITLE
Expected single value of attribute name of instance fta-fmea-application/function/28-00-00--F-1

### ISSUE THREAD

**Issue by LaChope** [kbss-cvut/fta-fmea#140]
After creating a new tree, I cannot create a new SNS event:

![image](https://github.com/kbss-cvut/fta-fmea/assets/57750426/dabdb636-8d2e-4021-b201-3220f15349a9)

Here is the error from backend:
```
[thread] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/fta-fmea] threw exception [Request processing failed: cz.cvut.kbss.jopa.exceptions.CardinalityConstraintViolatedException: Expected single value of attribute name of instance http://onto.fel.cvut.cz/ontologies/fta-fmea-application/function/28-00-00--F-1, but got multiple.] with root cause 
ava-fta-fmea-server        | cz.cvut.kbss.jopa.exceptions.CardinalityConstraintViolatedException: Expected single value of attribute name of instance http://onto.fel.cvut.cz/ontologies/fta-fmea-application/function/28-00-00--F-1, but got multiple.
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.SingularDataPropertyStrategy.verifyCardinalityConstraint(SingularDataPropertyStrategy.java:55)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.SingularDataPropertyStrategy.addAxiomValue(SingularDataPropertyStrategy.java:48)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.EntityConstructor.populateAttributes(EntityConstructor.java:140)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.EntityConstructor.reconstructEntity(EntityConstructor.java:92)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.EntityInstanceLoader.loadInstance(EntityInstanceLoader.java:94)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.TwoStepInstanceLoader.loadEntity(TwoStepInstanceLoader.java:45)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.loadEntityInternal(ObjectOntologyMapperImpl.java:139)
ava-fta-fmea-server        | 	at cz.cvut.kbss.jopa.oom.ObjectOntologyMapperImpl.getEntityFromCacheOrOntology(ObjectOntologyMapperImpl.java:266
```

**Comment by LaChope** [comment]
@blcham

**Comment by blcham** [comment]
@LaChope is it resolved?

**Comment by blcham** [comment]
resolved.
